In [1]:
import numpy as np

### 깊은복사, 얕은복사, 대입

#### 대입
- A와 B는 하나의 넘파이 배열을 가리킴

In [3]:
A = np.arange(12)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
B = A

In [5]:
A == B

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [6]:
A is B

True

In [7]:
A[0] = 100
B

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

### 깊은복사

In [8]:
A = np.arange(12)

In [9]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
B = A.copy()

In [11]:
A[0]= 100
A

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [12]:
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
C = A.view()

In [14]:
A[0] = 200

In [15]:
C

array([200,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

### 브로드 캐스팅
- 배열은 크기가 같은 배열끼리 연산
- 배열의 크기가 다를때 연산이 되는지 여부 확인

- 배열의 크기가 다를때 연산

A.shape =         (2,3,4,5)

B.shape = (5,) -> (1,1,1,5)

In [16]:
A = np.arange(120).reshape(2,3,4,5)
A.shape

(2, 3, 4, 5)

In [17]:
B = np.arange(5)
B.shape

(5,)

In [18]:
A+B

array([[[[  0,   2,   4,   6,   8],
         [  5,   7,   9,  11,  13],
         [ 10,  12,  14,  16,  18],
         [ 15,  17,  19,  21,  23]],

        [[ 20,  22,  24,  26,  28],
         [ 25,  27,  29,  31,  33],
         [ 30,  32,  34,  36,  38],
         [ 35,  37,  39,  41,  43]],

        [[ 40,  42,  44,  46,  48],
         [ 45,  47,  49,  51,  53],
         [ 50,  52,  54,  56,  58],
         [ 55,  57,  59,  61,  63]]],


       [[[ 60,  62,  64,  66,  68],
         [ 65,  67,  69,  71,  73],
         [ 70,  72,  74,  76,  78],
         [ 75,  77,  79,  81,  83]],

        [[ 80,  82,  84,  86,  88],
         [ 85,  87,  89,  91,  93],
         [ 90,  92,  94,  96,  98],
         [ 95,  97,  99, 101, 103]],

        [[100, 102, 104, 106, 108],
         [105, 107, 109, 111, 113],
         [110, 112, 114, 116, 118],
         [115, 117, 119, 121, 123]]]])

In [20]:
A = np.arange(6).reshape(2,1,3,1)
A.shape

(2, 1, 3, 1)

In [21]:
B = np.arange(3)
B.shape    #(1,1,1,3)

(3,)

In [22]:
A+B

array([[[[0, 1, 2],
         [1, 2, 3],
         [2, 3, 4]]],


       [[[3, 4, 5],
         [4, 5, 6],
         [5, 6, 7]]]])

In [23]:
A = np.arange(2).reshape(2,1)
A.shape

(2, 1)

In [25]:
B = np.arange(96).reshape(8,4,3)
B.shape

(8, 4, 3)

In [26]:
A+B

ValueError: operands could not be broadcast together with shapes (2,1) (8,4,3) 