#scipy.stats 사용 (범주와 범주로 검정 table)



#적합성검정   (관측빈도의 분포가 기대빈도의 분포를 따르는지 검정)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/ADPclass/ADP_book_ver01/main/data/titanic.csv')
df.to_csv('/content/drive/MyDrive/datasets/titanic.csv')

In [ ]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

   adult_male  embark_town  
0        True  Southampton  
1       False    Cherbourg  
2       False  Southampton  
3       False  Southampton  
4        True  Southampton

In [ ]:
df_t = df[df['survived']==1]
table = df_t[['sex']].value_counts() # 남성과 여성으로 값을 계산해서 분할
df_t.head()

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

   adult_male  embark_town  
1       False    Cherbourg  
2       False  Southampton  
3       False  Southampton  
8       False  Southampton  
9       False    Cherbourg

In [ ]:
table

sex   
female    233
male      109
dtype: int64

In [ ]:
from scipy.stats import chisquare
chi = chisquare(table, f_exp = [171, 171]) #기대빈도 (233+109)/2 ---> 171 적합성 검정은 관측빈도의 분포가 기대빈도의 분포를 따르는지 검정 예) 주사위의 값 확률은 1/6인지 확인
print('<적합도검정>\n', chi) # 남자와 여자의 비율이 같지 않다. 연구가설 채택

<적합도검정>
 Power_divergenceResult(statistic=44.95906432748538, pvalue=2.0119672574477235e-11)


# 독립성 검정 (두집단간에 연관성이 있는지 검정)

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/datasets/titanic.csv')
df.head()

Unnamed: 0  survived  pclass     sex   age  sibsp  parch     fare embarked  \
0           0         0       3    male  22.0      1      0   7.2500        S   
1           1         1       1  female  38.0      1      0  71.2833        C   
2           2         1       3  female  26.0      0      0   7.9250        S   
3           3         1       1  female  35.0      1      0  53.1000        S   
4           4         0       3    male  35.0      0      0   8.0500        S   

   class  adult_male  embark_town  
0  Third        True  Southampton  
1  First       False    Cherbourg  
2  Third       False  Southampton  
3  First       False  Southampton  
4  Third        True  Southampton

In [ ]:
table = pd.crosstab(df['class'], df['survived']) # 교차표는 범주형 데이터를 분리할 때에 유용함
table

survived    0    1
class             
First      80  136
Second     97   87
Third     372  119

In [ ]:
from scipy.stats import chi2_contingency
chi, p, df, expect = chi2_contingency(table)
print('Statistic:', chi)
print('p_value :', p)
print('df :', df)
print('expect: \n', expect) # 두변수간 연관성이 있다. 연구가설 채택 p_value : 4.549251711298793e-23

Statistic: 102.88898875696056
p_value : 4.549251711298793e-23
df : 2
expect: 
 [[133.09090909  82.90909091]
 [113.37373737  70.62626263]
 [302.53535354 188.46464646]]


# 동질성 검정  (여러 집단간 분포가 동질적인지 검정)

In [ ]:
import scipy.stats as stats
import numpy as np

# 예제 데이터셋: 지역별 정치적 경향에 대한 투표 수
# 행은 다른 지역을 나타내고, 열은 정치적 경향(보수, 중도, 진보)를 나타냄.
data = np.array([[30, 60, 10],  # 지역 A
                 [40, 50, 10],  # 지역 B
                 [30, 40, 30]]) # 지역 C

# 카이제곱 동질성 검정 수행
chi2, p, dof, expected = stats.chi2_contingency(data)

print(f"Chi-squared: {chi2}")
print(f"p-value: {p}")
print(f"Degrees of freedom: {dof}")
print(f"Expected frequencies:\n{expected}") #p-value: 0.000200420409482948 분포가 동질적이지 않으므로 연구가설 '지역 간에 정치적 경향의 분포가 다르다' 채택

Chi-squared: 22.0
p-value: 0.000200420409482948
Degrees of freedom: 4
Expected frequencies:
[[33.33333333 50.         16.66666667]
 [33.33333333 50.         16.66666667]
 [33.33333333 50.         16.66666667]]
