# CH02. Numpy  - 배열의 생성과 저장

---
* 날짜:
* 이름:


## 개념정리

`Numpy`(Numerical Python)는 포괄적인 함수, 난수생성, 선형대수학 등 고성능 수학 및 과학 계산에 효울적인 파이썬 라이브러리 입니다. 계산의 편리를 위한 배열(array)를 제공하며 이 배열은 파이썬의 list와 비슷하지만 다차원 데이터를 처리할 수 있고 더 효과적인 다차원 연산이 가능합니다. `Numpy`는 데이터과학의 핵심이라 할 수 있습니다.


> [NumPy Hompage](https://numpy.org/)



```
import numpy as np
```


In [ ]:
import numpy as np

---
### **(1) 리스트와 배열**
---

넘파이의 배열은 파이썬 리스트와 잘 호환 됩니다. 리스트를 생성해 봅시다. 

```
l = [1,2,3,4,5]
```


In [ ]:
l = [1,2,3,4,5]

* `np.array(l)` : 리스트 `l`을 넘파이 배열로 변환합니다. 

이제 이 리스트를 넘파이 배열로 변환해 봅시다. 

```
a = np.array(l)
```

In [ ]:
a = np.array(l)
a

array([1, 2, 3, 4, 5])

데이터 분석에서 중요한 것은 데이터의 형태 `shape` 입니다. 항상 데이터의 `shape`를 중간중간 확인하는 것을 잊지 마세요. 넘파이 배열에서는 형태를 `.shape`를 써서 확인합니다. 

* `.shape` : 넘파이 배열의 형태 (shape)를 반환합니다.

```
a.shape
```

In [ ]:
a,a.shape

(array([1, 2, 3, 4, 5]), (5,))

#### **| 연습문제**




**연습 01**

아래 그림과 같은 1차원 배열을 생성하고 `shape`를 확인해 보세요.

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0102-01.png?raw=trueA width=240>
</p>

In [ ]:
a1=np.array([1,4,1,0,1,2])

**연습 02**

아래 그림과 같은 2차원 배열을 생성하고 `shape`를 확인해 보세요. `shape`는 `(2,3)` 이 되게 하세요.

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0102-02.png?raw=trueA width=80>
</p>

In [ ]:
a2=np.array([[1,4],
             [1,0],
             [1,3],
             [2,2],
             [0,2]])
a2, a2.shape

(array([[1, 4],
        [1, 0],
        [1, 3],
        [2, 2],
        [0, 2]]), (5, 2))

**연습 03**

아래 그림과 같은 2차원 배열을 생성하고 `shape`를 확인해 보세요. `shape`는 `(6,2)` 가 되게 하세요.

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0102-03.png?raw=trueA width=120>
</p>

In [ ]:
a3=np.array([[1,4,1],
             [1,0,0]])
a3, a3.shape

(array([[1, 4, 1],
        [1, 0, 0]]), (2, 3))

**연습 04**

위에서 만든 배열을 겹쳐서 3차원으로 확장해 보았습니다. 아래 그림과 같은 3차원 배열을 생성하고 `shape`를 확인해 보세요.

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0102-04.png?raw=trueA width=120>
</p>

In [ ]:
a4=np.array([[[1,4,1],
               [1,0,0]],
              [[1,4,1],
               [1,0,0]]
              ])
a4, a4.shape

(array([[[1, 4, 1],
         [1, 0, 0]],
 
        [[1, 4, 1],
         [1, 0, 0]]]), (2, 2, 3))

---
### **(2) 기본 배열 생성**
---


* `np.empty(shape)` : `shape` 형태를 가진 빈 배열을 생성합니다. 


넘파이에서 배열을 생성하기 위해서는 기본적으로 생성할 배열에 대한 형태(shape)를 알고, 이를 기입해야 합니다. 

우선 위에서 만들었던 리스트와 같이 길이 5의 빈 배열을 만들어 봅시다. 


이렇게 생성된 배열에는 예상하지 못한 임의의 값이 들어있습니다. 

```
a = np.empty(5)
print(a)
```


In [ ]:
a=np.empty((5))
a, a.shape

(array([4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323, 2.5e-323]), (5,))

#### **| 초기값 정하기**

특정 형태의 배열을 만들고 초기값을 바로 세팅하고 싶다면 다음 함수를 사용합니다. 

* `np.zeros(shape)` : `shape` 형태를 가지고 모든 값이 `0`인 배열을 생성합니다. 
* `np.ones(shape)` : `shape` 형태를 가지고 모든 값이 `1`인 배열을 생성합니다.
* `np.full(shape, n)` : `shape` 형태를 가지고 모든 값이 `n`인 배열을 생성합니다.
* `np.eye(n)` : `n x n` 의 단위행렬(identity matrix)를 생성합니다. 


단위행렬이란 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬입니다. 

`np.eye`를 이용해 `3x3` 단위행렬을 만들고 어떻게 생겼는지 확인해 봅시다. 

```
np.eye(3)
```





In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

길이가 `10`이고 모든 값이 `2` 로 이루어진 배열을 생성해 봅시다. 

```
np.full(10, 2)

```

In [ ]:
np.full(10, 2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

#### **| 값 범위 정하기**

파이썬의 `range`와 마찬가지로 넘파이에도 값의 범위를 정해주는 함수들이 있습니다. 

* `np.arrange(start, end, step)` : 파이썬의 `range` 와 알고리즘이 똑같으며 값의 시작, 끝, 스텝을 지정할 수 있습니다. 

* `np.linspace(start, end, bins)` : 값의 시작, 끝, 그리고 이 사이를 몇개로 나눌 것인지 정합니다. 

* `np.logspace(start, end, bins)` : `np.linspace()`와 논리가 같으나 이를 로그 스케일로 생성합니다. 


```
np.arange(0,100,10)
```





In [ ]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

위와 똑같은 결과를 `linspace`를 이용해 얻기 위해서는 처음값 위 배열의 처음 값 `0`, 끝값`90`, 배열의 총 길이 `10`을 적어줘야 합니다.  

```
np.linspace(0,90,10)
```

In [ ]:
np.linspace(0,90,20)

array([ 0.        ,  4.73684211,  9.47368421, 14.21052632, 18.94736842,
       23.68421053, 28.42105263, 33.15789474, 37.89473684, 42.63157895,
       47.36842105, 52.10526316, 56.84210526, 61.57894737, 66.31578947,
       71.05263158, 75.78947368, 80.52631579, 85.26315789, 90.        ])


#### **| 형태 복사하기**


이미 생성되어 있는 배열과 똑같은 `shape`를 쉽게 만들기 위해서는 `_like` 함수를 사용합니다.

* `np.empty_like(a)` :배열 `a`와 같은 형태를 가진 빈 배열을 생성합니다. 
* `np.zeros_like(a)` : 배열 `a`와 같은 형태를 가지고 모든 값이 `0`인 배열을 생성합니다.  
* `np.ones_like(a)` : 배열 `a`와 같은 형태를 가지고 모든 값이 `1`인 배열을 생성합니다.  
* `np.full_like(a, n)` : 배열 `a`와 같은 형태를 가지고 모든 값이 `n`인 배열을 생성합니다.  



배열 `a`가 다음과 같이 정의 되어 있고 앞서 배운 `ones`를 이용해 `a`와 형태가 같지만 값이 모두 `1`인 배열 `b`를 만들어 봅시다. 

```
a = np.array([1,2,3,4,5,6])
b = np.ones(6)
print(b)
```


In [ ]:
a = np.array([1,2,3,4,5,6])
b = np.ones(6)
print(b)

[1. 1. 1. 1. 1. 1.]


이를 `np.oens_like`를 이용하면 아래와 같이 작성하면 됩니다.

보통 모방하는 배열 `a`의 정확한 형태를 모르거나, `a` 가 변수처럼 상황마다 달라 정확한 `shape`를 얻기 힘들때 유용하게 사용됩니다.

```
b = np.ones_like(a)
b
```

In [ ]:
b = np.ones_like(a)
b

array([1, 1, 1, 1, 1, 1])

---
### **(3) 랜덤 배열 생성**
---


| 함수 | 설명 |
|--|--|
| `seed` | 난수 발생시 시드 지정|
| `permutation` | 임의의 순열 반환|
| `shuffle` | 배열의 순서 섞기 |
| `randint` | 특정 범위의 표본(정수) 추출 |
| `random` | 균등분포를 따르는 0~1 사이 표본 추출|
| `rand` | 균등분포를 따르는 0~1 사이 표본 추출|
| `randn` | 표준정규분포를 따르는 표본 추출 |
| `normal` | 정규분포를 따르는 표본 추출 |
| `beta` | 베타분포를 따르는 표본 추출 |
| `chisquare` | 카이제곱분포를 따르는 표본 추출 |
| `gamma` | 감마분포를 따르는 표본 추출 |

파이썬 라이브러리 `random`과 비슷하게 넘파이에도 랜덤값을 얻는 다양한 함수를 제공합니다. 

각종 분포에 대한 자세한 설명은 이후 데이터분석 수업에서 알아보도록 하고, 지금은 다양한 분포에 대한 표본을 넘파이를 통해 추출할 수 있다는 것만 알고 계시면 됩니다.

이번 시간에는 간단한 함수 몇가지만 사용해 보도록 하겠습니다.

* `np.random.randint(i1,i2, shape)` `i1` 이상 `i2` 미만 랜덤값을 지니는 `shape` 형태의 배열을 생성합니다.

```
np.random.randint(0,10, (2,3))
```


In [ ]:
import random
np.random.randint(0,10, (2,3))

array([[5, 2, 9],
       [4, 8, 8]])

* `np.random.seed(n)` : 랜덤값 생성 규칙을 정합니다. (`n`은 자연수)정합니다. 


같은 `seed`에서 코드를 실행하면 똑같은 랜덤 값이 나오게 됩니다. 주로 코드를 실행하여 결과를 재현할 수 있도록 하기 위해 사용됩니다. 

```
np.random.seed(42)
np.random.randint(0,10, (2,3))
```

In [ ]:
np.random.seed(42)
np.random.randint(0,10, (2,3))

array([[6, 3, 7],
       [4, 6, 9]])

#### **| 균등 분포**

균등 분포란 모든 곳에서의 확률이 일정한 분포를 말합니다. 

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0102-05.PNG?raw=trueA width=300>
</p>


* `np.random.random((shape))` : `0~1` 사이 균등분포를 가지는  `shape` 형태의 배열을 생성합니다.

* `np.random.rand(shape)` : `0~1` 사이 균등분포를 가지는  `shape` 형태의 배열을 생성합니다.


```
print(np.random.random((3,2)))
print(np.random.rand(3,2))
```
`random.random`과 `random.rand` 둘다 똑같이 균등분포를 가지는 랜덤값을 출력합니다. 차이점은 `shape`를 `random.random`은 괄호 안에 넣어주어야 한다는 것입니다.

In [ ]:
print(np.random.random((3,2)))
print(np.random.rand(3,2))

[[0.15599452 0.05808361]
 [0.86617615 0.60111501]
 [0.70807258 0.02058449]]
[[0.96990985 0.83244264]
 [0.21233911 0.18182497]
 [0.18340451 0.30424224]]


#### **| 표준정규분포**

표준정규분포는 평균이 `0`이고 편차가 `1`인 가우스(정규) 분포를 뜻합니다. 

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0102-06.PNG?raw=trueA width=300>
</p>

* `np.random.randn(shape)` : 표준정규분포를 따르는 `shape` 형태의 배열을 생성합니다.


```
np.random.randn(3,2)
```


In [ ]:
np.random.randn(3,2)

array([[-2.61254901,  0.95036968],
       [ 0.81644508, -1.523876  ],
       [-0.42804606, -0.74240684]])

---
### **(4) 데이터 타입**
---

배열을 만들 때 어떤 값으로 채워져 있는지 이해해야 합니다. 

아래와 같이 배열 `a`,`b`,`c`를 생성합니다.

```
a = np.array([1,2,3,4])
b = np.zeros(4)
c = np.zeros_like(a)
print(a)
print(b)
print(c)
```

In [ ]:
a = np.array([1,2,3,4])
b = np.zeros(4)
c = np.zeros_like(a)
print(a)
print(b)
print(c)

[1 2 3 4]
[0. 0. 0. 0.]
[0 0 0 0]


`b`와 `c`는 `0`으로만 이루어져 있고 형태도 똑같습니다. 하지만 각 요소들은 다른 데이터 타입을 가지고 있습니다. 확인해 봅시다.

```
[type(x) for x in b], [type(x) for x in c]
```

In [ ]:
[type(x) for x in b], [type(x) for x in c]

([numpy.float64, numpy.float64, numpy.float64, numpy.float64],
 [numpy.int64, numpy.int64, numpy.int64, numpy.int64])

#### **| 여러가지 타입**

| 함수 | 설명 |
|--|--|
| `bool_` | 불리언(Boolean)|
| `int8(,16,32,64)` | 정수(-128 ~ 127)|
| `uint8(,16,32,64)` | 부호없는 정수 (0~ 255) |
| `int_` | =`int64`|
| `float16(,32,64)` | 소수점|
| `float_` | =`float64` |
| `complex64(,128)` | 복소수|
| `complex_` | =`complex128` |



* `np.---(dtype=type)` : 배열 생성시 `type`을 지정해 줍니다.

배열 `b`를 생성할 때 `int8` 타입으로 생성해 봅시다.

```
b = np.zeros(4, dtype='int8')
b, [type(x) for x in b]
```


In [ ]:
b = np.zeros(4, dtype='int8')
b, [type(x) for x in b]

(array([0, 0, 0, 0], dtype=int8),
 [numpy.int8, numpy.int8, numpy.int8, numpy.int8])

### **(5) 배열 입출력**



#### **| 저장**

* `np.save(save_path, a)` : 배열 `a` 한개를 경로 `save_path`에 저장합니다. 

```
np.save('test1', a)
```

In [ ]:
np.save('test1', a)

* `np.savez(save_path, a1, a2, ...)` : 배열  여러개를 경로 `save_path`에 저장합니다. 

```
np.savez('test2', a, a)
```

In [ ]:
np.savez('test2', a, b)

저장 시 각 배열에 대한 이름을 지정해 줄수 있습니다.
```
np.savez('test3', a1=a, a2=a)
```

In [ ]:
np.savez('test3', a1=a, a2=a)

#### **| 불러오기**

* `np.load(file_path)` : 넘파이 배열이 저장된 파일로부터 객체를 불러옵니다. 


```
a_npy = np.load('test.npy')
```

In [ ]:
test1 = np.load('test1.npy')
test1

array([1, 2, 3, 4])

배열이 여러개 들어간 `npz` 파일을 불러올 때는 어떤 이름으로 각 배열이 저장되어 있는지 확인해 볼 필요가 있습니다.

```
a_npz = np.load('test3.npz')
for a in a_npz:
  print(a)
```

In [ ]:
a_npz = np.load('test3.npz')
for idx in a_npz:
  print(idx)

a1
a2


이름 확인 후 인덱싱을 통해 각 배열에 접근 할 수 있습니다.

```
print(a_npz['a1'], a_npz['a2'])
```

In [ ]:
print(a_npz['a1'], a_npz['a2'])

[1 2 3 4] [1 2 3 4]


## 문제풀이
---


**예제 01**

아래그림과 같이 `shape`가 `(4)` 인 배열을 생성하고 `a1`로 바인딩 하세요.

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0102-07.png?raw=trueA width=180>
</p>

In [ ]:
a1=np.array([2,4,1,3])
a1

array([2, 4, 1, 3])

**예제 02**

`a1`와 `shape`가 똑같고 모든 값이 `1`인 배열을 생성하세요.

In [ ]:
np.ones(a1)

array([[[[1., 1., 1.]],

        [[1., 1., 1.]],

        [[1., 1., 1.]],

        [[1., 1., 1.]]],


       [[[1., 1., 1.]],

        [[1., 1., 1.]],

        [[1., 1., 1.]],

        [[1., 1., 1.]]]])

**예제 03**

`a1`와 모든 값이 같지만 `shape`가 `(1,4)`인 배열을 생성하세요.

In [ ]:
np.full_like(a1, 4)

array([4, 4, 4, 4])

**예제 04**

아래그림과 같이 `shape`가 `(4,2)`인 배열을 생성하고 `a2`로 바인딩 하세요.


<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0102-08.png?raw=trueA width=80>
</p>


In [ ]:
a2=np.array([[1,0],
             [1,0],
             [3,2],
             [1,1]])

**예제 05**

`a2`와 `shape`가 똑같고 모든 값이 `0`인 배열을 생성하세요.

In [ ]:
np.zeros_like(a2)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

**예제 06**

`a2`와 모든 값이 같지만 `shape`가 `(4,1,2)`인 배열을 생성하세요.

In [ ]:
a2=np.array([[[1,0]],
              [[1,0]],
              [[3,2]],
              [[1,1]]])
a2, a2.shape

(array([[[1, 0]],
 
        [[1, 0]],
 
        [[3, 2]],
 
        [[1, 1]]]), (4, 1, 2))

**예제 07**

`a2`와 모든 값이 같지만 아래와 같이 전치된 배열을 생성하세요.


<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0102-09.png?raw=trueA width=180>
</p>

In [ ]:
a3=np.array([[1,1,3,1],[0,0,2,1]])
a3, a3.shape

(array([[1, 1, 3, 1],
        [0, 0, 2, 1]]), (2, 4))

**예제 08**

모든 값이 `3`이고 `shape`가 `(5,1,2)`인 3차원 배열을 생성 후 `shape`를 확인하세요.

In [ ]:
a4=np.array([[[3,3]],
               [[3,3]],
               [[3,3]],
               [[3,3]],
               [[3,3]]])
a4, a4.shape

(array([[[3, 3]],
 
        [[3, 3]],
 
        [[3, 3]],
 
        [[3, 3]],
 
        [[3, 3]]]), (5, 1, 2))

**예제 09**

모든 값이 `3`이고 `shape`가 `(1,2,5)`인 3차원 배열을 생성 후 `shape`를 확인하세요.

In [ ]:
a5=np.array([[[3,3,3,3,3],[3,3,3,3,3]]])
a5, a5.shape

(array([[[3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3]]]), (1, 2, 5))

**예제 10**

모든 값이 3이고 shape가 `(2,1,3)`인 3차원 배열을 리스트를 이용해 직접 만들고 `shape`를 확인하세요.

In [ ]:
a6=np.array([[[3,3,3]],
             [[3,3,3]]])
a6, a6.shape

(array([[[3, 3, 3]],
 
        [[3, 3, 3]]]), (2, 1, 3))

**예제 11**

1에서 100까지 홀수값만을 가지는 배열을 `np.arange`를 이용해 생성하세요.


In [ ]:
a1=np.arange(1,100,2)
a1, a1.shape

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
        35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
        69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]),
 (50,))

**예제 12**

1에서 100까지 홀수값만을 가지는 배열을 `np.linspace`를 이용해 생성하세요.

In [ ]:
a1=np.linspace(1,99,50)
a1, a1.shape

(array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
        27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.,
        53., 55., 57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77.,
        79., 81., 83., 85., 87., 89., 91., 93., 95., 97., 99.]), (50,))

**예제 13**

`shape`가 `(5,5)`인 단위행렬(Identity matrix)를 생성하세요.


In [ ]:
a2=np.eye(5)
a2, a2.shape

(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]), (5, 5))

**예제 14**

`shape`가 `(10,5)`이고 균등분포를 따르는 배열을 생성하세요. 랜덤시드를 `42`로 정해주세요.


In [ ]:
np.random.seed(42)
np.random.randint(0,10, (10,5))

array([[6, 3, 7, 4, 6],
       [9, 2, 6, 7, 4],
       [3, 7, 7, 2, 5],
       [4, 1, 7, 5, 1],
       [4, 0, 9, 5, 8],
       [0, 9, 2, 6, 3],
       [8, 2, 4, 2, 6],
       [4, 8, 6, 1, 3],
       [8, 1, 9, 8, 9],
       [4, 1, 3, 6, 7]])

**예제 15**

`shape`가 `(10,5)`이고 표준정규분포를 따르는 배열을 생성하세요. 랜덤시드를 `42`로 정해주세요.


In [ ]:
a1=np.random.randn(10,5)
a1, a1.shape

(array([[-0.91942423,  1.54993441, -0.78325329, -0.32206152,  0.81351722],
        [-1.23086432,  0.22745993,  1.30714275, -1.60748323,  0.18463386],
        [ 0.25988279,  0.78182287, -1.23695071, -1.32045661,  0.52194157],
        [ 0.29698467,  0.25049285,  0.34644821, -0.68002472,  0.2322537 ],
        [ 0.29307247, -0.71435142,  1.86577451,  0.47383292, -1.1913035 ],
        [ 0.65655361, -0.97468167,  0.7870846 ,  1.15859558, -0.82068232],
        [ 0.96337613,  0.41278093,  0.82206016,  1.89679298, -0.24538812],
        [-0.75373616, -0.88951443, -0.81581028, -0.07710171,  0.34115197],
        [ 0.2766908 ,  0.82718325,  0.01300189,  1.45353408, -0.26465683],
        [ 2.72016917,  0.62566735, -0.85715756, -1.0708925 ,  0.48247242]]),
 (10, 5))

**예제 16**

`a1`의 `shape`와 데이터 `type`을 확인하세요. 모든 값을 `int64`로 변경하고 타입을 확인하세요.

In [ ]:
b = np.zeros(4, dtype='int64')
b, [type(x) for x in b]

(array([0, 0, 0, 0]), [numpy.int64, numpy.int64, numpy.int64, numpy.int64])

**예제 17**

`a2`의 `shape`와 데이터 `type`을 확인하세요. 모든 값을 `float64`로 변경하고 타입을 확인하세요.

**예제 18**

`a1`을 `.npy`파일로 저장하세요. 경로는 `02_quest18.npy` 입니다.

**예제 18**

`a1`과 `a2`를 `npz`파일로 저장하세요. 경로는 `02_quest19.npz` 입니다.

**예제 20**

위에서 저장한 파일을 모두 불러오고 저장된 배열들을 출력하세요.

**예제 21**

`ch02_quest18.npy`와 `ch02_quest19.npy` 를 깃허브 `results`폴더에 추가해 주세요.